<?php

const ST_BGA_GAME_SETUP = 1;

const ST_PLAYER_PLACE_WORKER = 2;
const ST_PLAYER_ACTIVATE_WORKER = 3;
const ST_PLAYER_TAKE_ACTION = 4;
const ST_PLAYER_AIRDROP_SELECT_SUPPLIES = 5;
const ST_PLAYER_AIRDROP_SELECT_FIELD = 6;   
const ST_PLAYER_SELECT_ROOM = 7;
const ST_PLAYER_SHOOT_MILICE = 8;

const ST_GAME_PLACE_PATROL = 60;
const ST_GAME_SAVE_ACTION = 62;
const ST_GAME_NEXT_WORKER = 63;

const ST_GAME_ROUND_END = 90;

const ST_BGA_GAME_END = 99;

?>